### ISSUE TITLE
build `wasm` app from this open source repository (cubzh/cubzh)

### ISSUE THREAD

**Issue by gdevillele** [cubzh/cubzh#556]
## Needs (deps of this task)
- [ ] bring `go/cu.bzh/cors` Go module to OSS repo
- [ ] bring VXFramework code to OSS repo

## TODO
- [ ] bring wasm project to OSS repo
- [ ] bash script to build (+ run, optionally) in docker
- [ ] dagger pipeline to build (+ run, optionally)
